services:
  react_e_commerce_main:
    build:
      context: ./React_E-Commerce-main
    ports:
      - "82:82"  # Host:Container port mapping
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists

networks:
  default:
    driver: bridge
